name: 'size-limit-action'
description: 'size-limit action'
author: 'Andres Alvarez <a.alvarez.sor@gmail.com>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  build_script:
    required: false
    description: 'a custom npm script to build'
  script:
    required: false
    default: "npx size-limit --json"
    description: "The script used to generate size-limit results"
  directory:
    required: false
    description: "a custom subdirectory"
runs:
  using: 'node20'
  main: 'dist/index.js'
